app:
  name: archivist-worker
debug: true
sqlite:
  path: /data/archivist.db
data:
  dir: /data
jina:
  enabled: false
  api:
    key: ""
llm:
  provider: anthropic
  model: claude-3-5-haiku-20241022
  api:
    key: ""
